<a href="https://www.kaggle.com/code/gowthamsevathan/titanic-machine-learning-computation?scriptVersionId=355273577" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

## Problem Statement
To analyze the Titanic dataset and determine the number of passengers who survived the disaster.

## Approach to the Problem Statement 
   * Import the Reqierd Library
   * Understand and explor the dataset
   * Handling missing values
   * Identify and Handle Outliers
   * Encoding Catogorical in to Numarical

## 1) Import the Reqierd Library

In [1]:
import pandas as pd 
import numpy as np

In [2]:
status_pes = pd.read_csv('/kaggle/input/competitions/titanic/gender_submission.csv')
test_data = pd.read_csv('/kaggle/input/competitions/titanic/test.csv')
train_data = pd.read_csv('/kaggle/input/competitions/titanic/train.csv')

In [3]:
import os

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/competitions/titanic/train.csv
/kaggle/input/competitions/titanic/test.csv
/kaggle/input/competitions/titanic/gender_submission.csv

In [4]:
df = pd.read_csv('/kaggle/input/competitions/titanic/gender_submission.csv')
df.head()

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

## 2) Understand and explor the dataset

In [5]:
def view_ser(data):
    print(data.head())
def data_type(data):
    print(data.dtypes)
def shape_sur(data):
    print(f'Row : {data.shape[0]} , Column : {data.shape[1]}')
def handle_missing(data):
    missing = data.isnull().sum()
    missing_per = missing / len(data) * 100
    result_data = pd.DataFrame({'Missing_Count': missing,'Missing_%' : missing_per})
    return result_data[result_data['Missing_Count']>0 ].sort_values(by='Missing_Count', ascending=False)
def check_traget(data,target_col):
    print(data[target_col].value_counts(normalize=True).round(2))
def dup_count(data):
    duplicate_col = data.duplicated().sum()
    print(f'Duplicate Columns : {duplicate_col}')
def all_data(data,target_col=None):
    print('='* 50)
    view_ser(data)
    print('=== DATA TYPE===')
    data_type(data)
    print('=== SHAPE ===')
    shape_sur(data)
    print('=== MISSING VALUES ===')
    print(handle_missing(data))
    print('===DUPLICATES===')
    dup_count(data)
    if check_traget:
        print(f'==={target_col}===')
        check_traget(data,target_col)

## Understanding of Gender Submission Table
1. There are two column the one is  *PassengerId* and Suvived
2. Total Row's 418 and column is 2
3. No missing values any of those so that's Grate thing to have clean data.
4. No duplicated from this table
5. Target column two feture (0 , 1) ---> 0 = Not Survied 1 = Survied
6. Target column is not balanced 0  = 0.64 and  1 = 0.36

In [6]:
all_data(status_pes,'Survived')

==================================================
   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1
=== DATA TYPE===
PassengerId    int64
Survived       int64
dtype: object
=== SHAPE ===
Row : 418 , Column : 2
=== MISSING VALUES ===
Empty DataFrame
Columns: [Missing_Count, Missing_%]
Index: []
===DUPLICATES===
Duplicate Columns : 0
===Survived===
Survived
0    0.64
1    0.36
Name: proportion, dtype: float64

## Understanding of Test Table
1. This table has good amount of record which contain 11 columns and 418 row's also we have (4 int) and (object 5) , (float 2) so total 11.
2. === MISSING VALUES ===
       Missing_Count  Missing_%
Cabin            327  78.229665
Age               86  20.574163
Fare               1   0.239234
as we can see here we do have a some of the column has NA or Null values we can have deep look here to handle missing values , it's important to understand them because when we train a model it can be predict wrong or get low accuracy.
3. again there no duplicate rows that's good thing.

In [7]:
def view_ser(data):
    print(data.head())
def data_type(data):
    print(data.dtypes)
def shape_sur(data):
    print(f'Row : {data.shape[0]} , Column : {data.shape[1]}')
def handle_missing(data):
    missing = data.isnull().sum()
    missing_per = missing / len(data) * 100
    result_data = pd.DataFrame({'Missing_Count': missing,'Missing_%' : missing_per})
    return result_data[result_data['Missing_Count']>0 ].sort_values(by='Missing_Count', ascending=False)
def dup_count(data):
    duplicate_col = data.duplicated().sum()
    print(f'Duplicate Columns : {duplicate_col}')
def all_data(data):
    print('='* 50)
    view_ser(data)
    print('=== DATA TYPE===')
    data_type(data)
    print('=== SHAPE ===')
    shape_sur(data)
    print('=== MISSING VALUES ===')
    print(handle_missing(data))
    print('===DUPLICATES===')
    dup_count(data)

In [8]:
all_data(test_data)

==================================================
   PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female
2          894       2                     Myles, Mr. Thomas Francis    male
3          895       3                              Wirz, Mr. Albert    male
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked
0  34.5      0      0   330911   7.8292   NaN        Q
1  47.0      1      0   363272   7.0000   NaN        S
2  62.0      0      0   240276   9.6875   NaN        Q
3  27.0      0      0   315154   8.6625   NaN        S
4  22.0      1      1  3101298  12.2875   NaN        S
=== DATA TYPE===
PassengerId      int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object
=== SHAPE ===
Row : 418 , Column : 11
=== MISSING VALUES ===
       Missing_Count  Missing_%
Cabin            327  78.229665
Age               86  20.574163
Fare               1   0.239234
===DUPLICATES===
Duplicate Columns : 0

In [9]:
#check how each data type's are there in the table 
print(test_data.dtypes.value_counts())

object     5
int64      4
float64    2
Name: count, dtype: int64

In [10]:
all_data(train_data)

==================================================
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
=== DATA TYPE===
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object
=== SHAPE ===
Row : 891 , Column : 12
=== MISSING VALUES ===
          Missing_Count  Missing_%
Cabin               687  77.104377
Age                 177  19.865320
Embarked              2   0.224467
===DUPLICATES===
Duplicate Columns : 0

In [11]:
print(train_data.dtypes.value_counts())

int64      5
object     5
float64    2
Name: count, dtype: int64

## 3) Handling missing values
1. === MISSING VALUES ===
          Missing_Count  Missing_%
Cabin               687  77.104377
Age                 177  19.865320
Embarked              2   0.224467

2. need to handle the missing record's in the

In [12]:
def handling_missing(data,col, strategy ='mean'):
    if strategy == 'mean':
        data[col] = data[col].fillna(data[col].mean()).round(1)
    elif strategy == 'median':
        data[col] = data[col].fillna(data[col].median())
    elif strategy == 'mode':
        data[col] = data[col].fillna(data[col].mode()[0])
    elif strategy == 'drop_col':
        data[col] = data.drop(columns = [col])
    elif strategy == 'drop_row' : 
        data[col] = data.dropna(subset=[col])
    return data

Hadling the missing value 'AGE'

In [13]:
handling_missing(test_data,'Age','median')

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,27.0,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,27.0,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,27.0,1,1,2668,22.3583,NaN,C

In [14]:
handling_missing(test_data,'Cabin','mode')

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,B57 B59 B63 B66,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,B57 B59 B63 B66,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,B57 B59 B63 B66,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,B57 B59 B63 B66,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,B57 B59 B63 B66,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,27.0,0,0,A.5. 3236,8.0500,B57 B59 B63 B66,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,B57 B59 B63 B66,S
416,1308,3,"Ware, Mr. Frederick",male,27.0,0,0,359309,8.0500,B57 B59 B63 B66,S
417,1309,3,"Peter, Master. Michael J",male,27.0,1,1,2668,22.3583,B57 B59 B63 B66,C

In [15]:
handling_missing(test_data, 'Embarked', 'mode')

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,B57 B59 B63 B66,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,B57 B59 B63 B66,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,B57 B59 B63 B66,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,B57 B59 B63 B66,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,B57 B59 B63 B66,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,27.0,0,0,A.5. 3236,8.0500,B57 B59 B63 B66,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,B57 B59 B63 B66,S
416,1308,3,"Ware, Mr. Frederick",male,27.0,0,0,359309,8.0500,B57 B59 B63 B66,S
417,1309,3,"Peter, Master. Michael J",male,27.0,1,1,2668,22.3583,B57 B59 B63 B66,C

## Discuss about working or handling with missng data
1. so the dataset had some of the missing values 'Age' and 'Cabin' , 'Embarked'.
2. 'Age' used to manage the record with the mean it make sence to fill with the avg.
3. 'Cabin' we can do some analysis , so we filled with mode frequent values.
4. 'Embarked' again mode

In [16]:
handling_missing(train_data,'Age','median')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [17]:
handling_missing(train_data,'Cabin','mode')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,B96 B98,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,B96 B98,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,B96 B98,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,B96 B98,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,B96 B98,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,B96 B98,Q

In [18]:
handling_missing(train_data, 'Embarked', 'mode')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,B96 B98,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,B96 B98,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,B96 B98,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,B96 B98,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,B96 B98,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,B96 B98,Q

## 4) Identify or Handling Outer layer
let understand the how our data is far from rest of the data
* [IQR = Q3 -Q1](http://)
* [Q1 = q1 - 1.5 (IQR)](http://)
* [Q3 = q3 + 1.5 (IQR)](http://)
* Babies/toddlers (0.8, 1, 2 years old)
* Older adults (55–74 years old)

In [19]:
def identif_outlayer(data, col):
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 *IQR
    upper = Q3 + 1.5 *IQR
    outlayer = data[(data[col] < lower) | (data[col] > upper)]
    #outlayer = data[(data[col] < lower) | (data[col] > upper)]
    print(f'{col} : {len(outlayer)} outlayer (outside{lower:.1f} to {upper:.1f})')
    #print(f'{col}: {len(outlayer)} outlayer (outside {lower:.1f} to {upper:.1f})')
    return outlayer
#outlayer_rows = identif_outlayer(train_data, 'Age')
#print(outlayer_rows[['Age', 'Survived', 'Pclass']])

In [20]:
pd.set_option('display.max_rows', None)

outlayer_rows = identif_outlayer(train_data, 'Age')
outlayer_rows[['Age', 'Survived', 'Pclass']].head()

Age : 66 outlayer (outside2.5 to 54.5)

     Age  Survived  Pclass
7    2.0         0       3
11  58.0         1       1
15  55.0         1       2
16   2.0         0       3
33  66.0         0       2

*  Total outliers = 66
*   It's not just adults  children are included too
*    This shows Age values are spread wide, mixed between very young and very old

## Encoding Catogorical into numarical
why do we needed ??
1. Machine can't understand the Text so it need Numbers to perform the some action's so we need to make them into numarical it like [Calcilater](http://)

2. the first one is [sex](http://) it as a two feture so we can use the ENCODING

3. Embarked: 3 categories → one-hot encoding (separate 0/1 columns)

In [21]:
#Sex: only 2 categories → convert directly to 0/1
test_data['Sex'] = test_data['Sex'].map({'male' : 0, 'female' :1})

#Embarked: 3 categories → one-hot encoding (separate 0/1 columns)
#test_data = pd.get_dummies(test_data,columns=['Embarked'],drop_first= True )
train_data = pd.get_dummies(train_data, columns=['Embarked'], drop_first=True)

In [22]:
print(test_data.columns)

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [23]:
print(test_data.columns.tolist())
print(train_data.columns.tolist())

['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked_Q', 'Embarked_S']

In [24]:
train_data['Sex'] = train_data['Sex'].map({'male' : 0 , 'female' : 1})

In [25]:
#understanding the each of those  distribution 
sex_serviel = train_data.groupby('Sex')['Survived'].mean().round(2)*100
p_class_servied=train_data.groupby('Pclass')['Survived'].mean().round(2)*100
print('How many of the Survived from each Category  :',sex_serviel)
print('Chance of serving in the each class: ',p_class_servied)

How many of the Survived from each Category  : Sex
0    19.0
1    74.0
Name: Survived, dtype: float64
Chance of serving in the each class:  Pclass
1    63.0
2    47.0
3    24.0
Name: Survived, dtype: float64

In [26]:
train_data.groupby('Sex')['Survived'].sum()
male = 109
female = 233
servived_both = male + female
print(servived_both)

342

1. importent point survival rate is 63% /100 only 36% of people only Survived

2. so here we can see that the servivel of the each category male = 19% and female = 74% has seevied

3. servied of the passengers is 342/891

4. P_class base survived  is

   * class 1 = 64%/100
   * class 2 = 47%
   * class 3 = 24%

## AgeGroup

In [27]:
train_data['AgeGroup'] = pd.cut(train_data['Age'], bins=[0, 12 ,18, 40, 80], labels=['child','Teen', 'Audlt','Senior'])
train_data.groupby('AgeGroup',observed=True)['Survived'].mean().round(2)*100

AgeGroup
child     58.0
Teen      43.0
Audlt     36.0
Senior    37.0
Name: Survived, dtype: float64

In [28]:
#proxy variable
train_data['Fare_Group'] = pd.cut(train_data['Fare'],bins=[0,10,50,100,520],labels=['Low', 'Medium', 'High', 'VeryHigh'])
                                                     
train_data.groupby('Fare_Group',observed=True)['Survived'].mean().round(2)*100

Fare_Group
Low         21.0
Medium      42.0
High        65.0
VeryHigh    74.0
Name: Survived, dtype: float64